create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,name text not null check(char_length(trim(name)) between 2 and 24),home_district text not null check(home_district in('kasaragod','kannur','wayanad','kozhikode','malappuram','palakkad','thrissur','ernakulam','idukki','kottayam','alappuzha','pathanamthitta','kollam','thiruvananthapuram')),gender text not null check(gender in('male','female')),created_at timestamptz not null default now());
alter table public.profiles enable row level security;
create policy "Profiles visible to players" on public.profiles for select to authenticated using(true);
create policy "Create own profile" on public.profiles for insert to authenticated with check((select auth.uid())=id);
create policy "Update own profile" on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);
create table if not exists public.follow_requests(id uuid primary key default gen_random_uuid(),requester_id uuid not null references public.profiles(id) on delete cascade,target_id uuid not null references public.profiles(id) on delete cascade,status text not null default 'pending' check(status in('pending','accepted','rejected')),created_at timestamptz not null default now(),check(requester_id<>target_id));
create unique index if not exists one_connection_per_pair on public.follow_requests(least(requester_id,target_id),greatest(requester_id,target_id));
alter table public.follow_requests enable row level security;
create policy "Read own requests" on public.follow_requests for select to authenticated using((select auth.uid()) in(requester_id,target_id));
create policy "Send requests" on public.follow_requests for insert to authenticated with check((select auth.uid())=requester_id and status='pending');
create policy "Answer requests" on public.follow_requests for update to authenticated using((select auth.uid())=target_id) with check((select auth.uid())=target_id and status in('accepted','rejected'));
create policy "Delete own requests" on public.follow_requests for delete to authenticated using((select auth.uid()) in(requester_id,target_id));
create table if not exists public.district_messages(id uuid primary key default gen_random_uuid(),room text not null default 'kottayam' check(room='kottayam'),sender_id uuid not null references public.profiles(id) on delete cascade,body text not null check(char_length(trim(body)) between 1 and 1000),created_at timestamptz not null default now());
alter table public.district_messages enable row level security;
create policy "Read community chat" on public.district_messages for select to authenticated using(exists(select 1 from public.profiles where id=(select auth.uid())));
create policy "Send community chat" on public.district_messages for insert to authenticated with check(sender_id=(select auth.uid()) and room='kottayam');
create table if not exists public.dm_messages(id uuid primary key default gen_random_uuid(),sender_id uuid not null references public.profiles(id) on delete cascade,receiver_id uuid not null references public.profiles(id) on delete cascade,body text not null check(char_length(trim(body)) between 1 and 1000),created_at timestamptz not null default now(),check(sender_id<>receiver_id));
alter table public.dm_messages enable row level security;
create policy "Connections read DMs" on public.dm_messages for select to authenticated using(((select auth.uid()) in(sender_id,receiver_id)) and exists(select 1 from public.follow_requests f where f.status='accepted' and ((f.requester_id=sender_id and f.target_id=receiver_id) or(f.requester_id=receiver_id and f.target_id=sender_id))));
create policy "Connections send DMs" on public.dm_messages for insert to authenticated with check(sender_id=(select auth.uid()) and exists(select 1 from public.follow_requests f where f.status='accepted' and ((f.requester_id=sender_id and f.target_id=receiver_id) or(f.requester_id=receiver_id and f.target_id=sender_id))));
create index if not exists district_messages_room_time on public.district_messages(room,created_at desc);
create index if not exists dm_sender_time on public.dm_messages(sender_id,created_at desc);
create index if not exists dm_receiver_time on public.dm_messages(receiver_id,created_at desc);
do $$ begin
 begin alter publication supabase_realtime add table public.district_messages; exception when duplicate_object then null; end;
 begin alter publication supabase_realtime add table public.dm_messages; exception when duplicate_object then null; end;
 begin alter publication supabase_realtime add table public.follow_requests; exception when duplicate_object then null; end;
end $$;
