import * as THREE from "three";
import { createClient } from "@supabase/supabase-js";
import india from "./india-locations.json";
import "./style.css";

const $=id=>document.getElementById(id);
const states=[...india.states].sort((a,b)=>a.state.localeCompare(b.state));
function fillStates(id){const select=$(id);for(const item of states){const option=new Option(item.state,item.state);select.add(option)}select.value="Kerala"}
function fillDistricts(stateId,districtId,selected="Kottayam"){const state=$(stateId).value,item=states.find(s=>s.state===state),select=$(districtId);select.replaceChildren();for(const district of item?.districts||[])select.add(new Option(district,district));if([...select.options].some(o=>o.value===selected))select.value=selected}
fillStates("home-state");fillStates("travel-state");fillDistricts("home-state","home-district");fillDistricts("travel-state","travel-district");
$("home-state").onchange=()=>fillDistricts("home-state","home-district","");
$("travel-state").onchange=()=>fillDistricts("travel-state","travel-district","");
let timer;function notify(message){$("notice").textContent=message;$("notice").style.display="block";clearTimeout(timer);timer=setTimeout(()=>$("notice").style.display="none",5000)}
async function safe(fn){try{return await fn()}catch(e){console.error(e);notify(e.message||"Something went wrong")}}
const url=import.meta.env.VITE_SUPABASE_URL;
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=url&&key?createClient(url,key):null;
let user,profile,activeDM=null,profiles=new Map(),requests=[],worldStarted=false;
const authScreens=["login","signup","forgot","new-password-screen"];
function showAuth(id){for(const name of authScreens)$(name).hidden=name!==id}
async function boot(session){user=session.user;const{data,error}=await supabase.from("profiles").select("*").eq("id",user.id).maybeSingle();if(error)throw error;if(data){profile=data;enterWorld()}else{notify("Finish account creation from the confirmation email.");showAuth("login")}}
if(supabase){
 $("login-form").onsubmit=e=>safe(async()=>{e.preventDefault();const{data,error}=await supabase.auth.signInWithPassword({email:$("login-email").value.trim(),password:$("login-password").value});if(error)throw error;await boot(data.session)});
 $("signup-form").onsubmit=e=>safe(async()=>{e.preventDefault();const metadata={username:$("username").value.trim().toLowerCase(),name:$("player-name").value.trim(),home_state:$("home-state").value,home_district:$("home-district").value,gender:$("gender").value};const{data,error}=await supabase.auth.signUp({email:$("signup-email").value.trim(),password:$("signup-password").value,options:{emailRedirectTo:location.origin,data:metadata}});if(error){if(error.message.toLowerCase().includes("database"))throw new Error("Username may already be taken. Try another username.");throw error}if(data.session)await boot(data.session);else{showAuth("login");notify("Confirmation email sent. Confirm it, then login.")}});
 $("forgot-form").onsubmit=e=>safe(async()=>{e.preventDefault();const{error}=await supabase.auth.resetPasswordForEmail($("forgot-email").value.trim(),{redirectTo:location.origin});if(error)throw error;showAuth("login");notify("Password reset link sent to your email.")});
 $("new-password-form").onsubmit=e=>safe(async()=>{e.preventDefault();const{error}=await supabase.auth.updateUser({password:$("new-password").value});if(error)throw error;notify("Password changed successfully.");location.href=location.origin});
 $("show-signup").onclick=()=>showAuth("signup");$("show-forgot").onclick=()=>showAuth("forgot");document.querySelectorAll(".back-login").forEach(b=>b.onclick=()=>showAuth("login"));
 supabase.auth.onAuthStateChange((event,session)=>{if(event==="PASSWORD_RECOVERY")showAuth("new-password-screen");else if(session&&!worldStarted)setTimeout(()=>safe(()=>boot(session)),0)});
 safe(async()=>{const{data:{session}}=await supabase.auth.getSession();if(session)await boot(session)});
}else notify("Database connection is missing.");
$("logout").onclick=()=>safe(async()=>{await supabase.auth.signOut();location.reload()});

let scene,camera,renderer,avatar,car,ground,driving=false,vertical=0,jumpHeight=0,wallet=0,job=false,activities=0,moveTarget=null;const keys=new Set();
const material=color=>new THREE.MeshStandardMaterial({color,roughness:.82});
function box(parent,w,h,d,color,x=0,y=0,z=0){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(color));mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);return mesh}
function tree(x,z){const g=new THREE.Group();box(g,.3,2,.3,0x724627,0,1,0);const crown=new THREE.Mesh(new THREE.ConeGeometry(1.4,2.8,7),material(0x197744));crown.position.y=3;g.add(crown);g.position.set(x,0,z);scene.add(g)}
function sign(text){const c=document.createElement("canvas");c.width=512;c.height=96;const x=c.getContext("2d");x.fillStyle="#06271f";x.fillRect(0,0,512,96);x.fillStyle="#effff8";x.font="bold 30px sans-serif";x.textAlign="center";x.fillText(text,256,60);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c)}));s.scale.set(6,1.1,1);return s}
function building(x,z,color,name){const g=new THREE.Group();box(g,5,3.6,4,color,0,1.8,0);box(g,1.1,2,.2,0x3b2418,0,1,2.1);const s=sign(name);s.position.y=4.3;g.add(s);g.position.set(x,0,z);scene.add(g)}
function person(){const g=new THREE.Group();box(g,1,1.7,.65,profile.gender==="female"?0xbd3f7c:0x35d48f,0,1.65,0);const h=new THREE.Mesh(new THREE.SphereGeometry(.43,16,12),material(0xb97954));h.position.y=2.85;g.add(h);box(g,.32,1.2,.35,0x22304c,-.28,.6,0);box(g,.32,1.2,.35,0x22304c,.28,.6,0);return g}
function setupWorld(){scene=new THREE.Scene();scene.background=new THREE.Color(0x8bd0dd);scene.fog=new THREE.Fog(0x8bd0dd,50,120);camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,220);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;$("world").append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xd8ffff,0x315226,2.4));const sun=new THREE.DirectionalLight(0xfff1c5,2.8);sun.position.set(-20,35,10);sun.castShadow=true;scene.add(sun);ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),material(0x367b48));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);box(scene,10,.12,180,0x2b3435,0,.07,0);box(scene,180,.12,10,0x2b3435,0,.08,0);for(let i=-75;i<=75;i+=12){box(scene,.3,.16,4,0xffe46b,-1,.15,i);box(scene,.3,.16,4,0xffe46b,1,.15,i)}for(let i=0;i<38;i++)tree((Math.random()-.5)*150,(Math.random()-.5)*150);building(-12,-12,0xf1a84a,"TTK STORES · KOTTAYAM");building(14,-18,0xf6e5b7,"KERALA CAFE");building(-16,18,0xe9f0e7,"COMMUNITY HALL");building(19,17,0xe07855,"MARKET");avatar=person();avatar.position.set(0,0,5);scene.add(avatar);car=new THREE.Group();box(car,2.4,.7,4,0xe3aa18,0,.75,0);box(car,2,.75,2,0x185e65,0,1.35,-.2);car.position.set(5,0,3);scene.add(car);camera.position.set(0,8,13);renderer.domElement.addEventListener("pointerup",setMovementTarget);addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});animate()}
function setMovementTarget(event){const rect=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((event.clientX-rect.left)/rect.width*2-1,-((event.clientY-rect.top)/rect.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObject(ground)[0];if(hit)moveTarget=hit.point.clone()}
function animate(){requestAnimationFrame(animate);const dt=Math.min(.04,1/60),target=driving?car:avatar;let x=0,z=0;if(keys.has("ArrowLeft")||keys.has("KeyA"))x--;if(keys.has("ArrowRight")||keys.has("KeyD"))x++;if(keys.has("ArrowUp")||keys.has("KeyW"))z--;if(keys.has("ArrowDown")||keys.has("KeyS"))z++;if(x||z){moveTarget=null;const n=Math.hypot(x,z),speed=driving?12:6;target.position.x+=x/n*speed*dt;target.position.z+=z/n*speed*dt;target.rotation.y=Math.atan2(x,z)}else if(moveTarget){const dx=moveTarget.x-target.position.x,dz=moveTarget.z-target.position.z,n=Math.hypot(dx,dz);if(n<.25)moveTarget=null;else{const step=Math.min(n,(driving?12:6)*dt);target.position.x+=dx/n*step;target.position.z+=dz/n*step;target.rotation.y=Math.atan2(dx,dz)}}if(!driving){vertical-=22*dt;jumpHeight+=vertical*dt;if(jumpHeight<0){jumpHeight=0;vertical=0}avatar.position.y=jumpHeight}else avatar.position.copy(car.position).add(new THREE.Vector3(0,1.4,0));camera.position.lerp(new THREE.Vector3(target.position.x,target.position.y+7,target.position.z+11),.08);camera.lookAt(target.position.x,target.position.y+1,target.position.z);renderer.render(scene,camera)}
addEventListener("keydown",e=>{keys.add(e.code);if(e.code==="Space"&&!jumpHeight)vertical=8});addEventListener("keyup",e=>keys.delete(e.code));$("jump").onclick=()=>{if(!jumpHeight)vertical=8};$("drive").onclick=()=>{if(!driving&&avatar.position.distanceTo(car.position)>7)return notify("Walk closer to the auto-rickshaw.");driving=!driving;$("drive").textContent=driving?"Exit":"Drive"};$("job").onclick=()=>safe(async()=>{if(job){job=false;wallet+=100;profile.points=wallet;activities++;const{error}=await supabase.from("profiles").update({points:wallet}).eq("id",user.id);if(error)throw error;notify("Delivery completed. 100 points earned!")}else{job=true;notify("Delivery started. Explore town, then press Job again.")}updateHud()});
function updateHud(){wallet=profile.points??wallet;const level=Math.floor(wallet/500)+1;$("player-info").textContent=`${profile.name} · @${profile.username} · Lv. ${level}`;$("wallet").textContent=`${wallet.toLocaleString("en-IN")} points`;$("mission-info").textContent=`Next level at ${level*500} points`;$("job-info").textContent=job?"Delivery active — explore and press Job to finish.":`Explore ${profile.home_district}, ${profile.home_state}.`;$("location").textContent=`${profile.home_district}, ${profile.home_state}`;$("chat-title").textContent=`${profile.home_district} community`}

async function refreshPeople(){if(!user)return;const[p,r]=await Promise.all([supabase.from("profiles").select("id,username,name,home_state,home_district,gender").limit(100),supabase.from("follow_requests").select("*")]);if(p.error)throw p.error;if(r.error)throw r.error;profiles=new Map(p.data.map(v=>[v.id,v]));requests=r.data;renderPeople()}
function button(parent,label,fn,secondary=false){const b=document.createElement("button");b.textContent=label;if(secondary)b.className="secondary";b.onclick=()=>safe(fn);parent.append(b)}
function renderPeople(){const root=$("people");root.replaceChildren();const list=[...profiles.values()].filter(p=>p.id!==user.id);if(!list.length){root.textContent="No other profiles yet.";return}for(const p of list){const card=document.createElement("div");card.className="person";const title=document.createElement("strong");title.textContent=`${p.name} · @${p.username}`;const district=document.createElement("small");district.textContent=`${p.home_district}, ${p.home_state}`;const actions=document.createElement("div");actions.className="row";const req=requests.find(r=>(r.requester_id===user.id&&r.target_id===p.id)||(r.target_id===user.id&&r.requester_id===p.id));if(!req)button(actions,"Follow",async()=>{const{error}=await supabase.from("follow_requests").insert({requester_id:user.id,target_id:p.id});if(error)throw error;refreshPeople()});else if(req.status==="accepted"){button(actions,"Message",async()=>{activeDM=p.id;$("chat-title").textContent=p.name;loadMessages()});button(actions,"Disconnect",async()=>{await supabase.from("follow_requests").delete().eq("id",req.id);activeDM=null;refreshPeople()},true)}else if(req.target_id===user.id&&req.status==="pending"){button(actions,"Accept",async()=>{await supabase.from("follow_requests").update({status:"accepted"}).eq("id",req.id);refreshPeople()});button(actions,"Reject",async()=>{await supabase.from("follow_requests").update({status:"rejected"}).eq("id",req.id);refreshPeople()},true)}else{const s=document.createElement("small");s.textContent=req.status;actions.append(s)}card.append(title,district,actions);root.append(card)}}
const roomName=()=>`${profile.home_state}::${profile.home_district}`;
async function loadMessages(){if(!user)return;const q=activeDM?supabase.from("dm_messages").select("*").or(`and(sender_id.eq.${user.id},receiver_id.eq.${activeDM}),and(sender_id.eq.${activeDM},receiver_id.eq.${user.id})`).order("created_at",{ascending:false}).limit(50):supabase.from("district_messages").select("*").eq("room",roomName()).order("created_at",{ascending:false}).limit(50);const{data,error}=await q;if(error)throw error;const root=$("messages");root.replaceChildren();for(const m of [...data].reverse()){const row=document.createElement("div");row.className="message";const head=document.createElement("strong");head.textContent=`${profiles.get(m.sender_id)?.name||"Player"} · ${new Date(m.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}`;const body=document.createElement("span");body.textContent=m.body;row.append(head,body);root.append(row)}root.scrollTop=root.scrollHeight}
$("chat-form").onsubmit=e=>safe(async()=>{e.preventDefault();if(!user)return;const body=$("chat-input").value.trim();const result=activeDM?await supabase.from("dm_messages").insert({sender_id:user.id,receiver_id:activeDM,body}):await supabase.from("district_messages").insert({room:roomName(),sender_id:user.id,body});if(result.error)throw result.error;$("chat-input").value="";loadMessages()});$("group").onclick=()=>{activeDM=null;$("chat-title").textContent=`${profile.home_district} community`;safe(loadMessages)};$("refresh").onclick=()=>safe(refreshPeople);
$("travel").onclick=()=>{profile.home_state=$("travel-state").value;profile.home_district=$("travel-district").value;$("location").textContent=`${profile.home_district}, ${profile.home_state}`;$("chat-title").textContent=`${profile.home_district} community`;notify(`Fast travelled to ${profile.home_district}, ${profile.home_state}.`);safe(loadMessages)};$("menu").onclick=()=>$("sidebar").classList.add("open");$("close").onclick=()=>$("sidebar").classList.remove("open");
async function enterWorld(){if(worldStarted)return;worldStarted=true;for(const name of authScreens)$(name).hidden=true;$("game").hidden=false;setupWorld();updateHud();if(user){await refreshPeople();await loadMessages();supabase.channel(`world-${user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"district_messages"},()=>!activeDM&&safe(loadMessages)).on("postgres_changes",{event:"*",schema:"public",table:"dm_messages"},()=>activeDM&&safe(loadMessages)).on("postgres_changes",{event:"*",schema:"public",table:"follow_requests"},()=>safe(refreshPeople)).subscribe()}}
