import * as THREE from "three";
import { createClient } from "@supabase/supabase-js";
import "./style.css";

const $=id=>document.getElementById(id);
const districts=[["kasaragod","Kasaragod",12.5,74.99],["kannur","Kannur",11.87,75.37],["wayanad","Wayanad",11.61,76.08],["kozhikode","Kozhikode",11.26,75.78],["malappuram","Malappuram",11.05,76.07],["palakkad","Palakkad",10.79,76.65],["thrissur","Thrissur",10.53,76.21],["ernakulam","Ernakulam",9.98,76.3],["idukki","Idukki",9.85,76.97],["kottayam","Kottayam",9.59,76.52],["alappuzha","Alappuzha",9.49,76.34],["pathanamthitta","Pathanamthitta",9.26,76.78],["kollam","Kollam",8.89,76.61],["thiruvananthapuram","Thiruvananthapuram",8.52,76.94]].map(([id,name,lat,lon])=>({id,name,lat,lon}));
for(const selectId of ["home-district","travel-district"])for(const d of districts){const o=document.createElement("option");o.value=d.id;o.textContent=d.name;$(selectId).append(o)}
$("home-district").value=$("travel-district").value="kottayam";
let timer;function notify(message){$("notice").textContent=message;$("notice").style.display="block";clearTimeout(timer);timer=setTimeout(()=>$("notice").style.display="none",5000)}
async function safe(fn){try{return await fn()}catch(e){console.error(e);notify(e.message||"Something went wrong")}}
const url=import.meta.env.VITE_SUPABASE_URL;
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=url&&key?createClient(url,key):null;
let user,profile,activeDM=null,profiles=new Map(),requests=[],worldStarted=false;

if(supabase){
 $("login-form").onsubmit=e=>safe(async()=>{e.preventDefault();const{error}=await supabase.auth.signInWithOtp({email:$("email").value.trim(),options:{emailRedirectTo:location.origin}});if(error)throw error;notify("Login link sent. Check inbox and spam.")});
 $("profile-form").onsubmit=e=>safe(async()=>{e.preventDefault();const{data,error}=await supabase.from("profiles").insert({id:user.id,name:$("player-name").value.trim(),home_district:$("home-district").value,gender:$("gender").value}).select().single();if(error)throw error;profile=data;enterWorld()});
 supabase.auth.onAuthStateChange((_event,session)=>session&&setTimeout(()=>boot(session),0));
 supabase.auth.getSession().then(({data})=>data.session&&boot(data.session));
}else{$("login-form").innerHTML='<p class="muted">Supabase is not configured. You can still test the world.</p><button type="button" id="demo">Enter demo</button>';$("demo").onclick=()=>{profile={id:"demo",name:"Guest Explorer",gender:"male",home_district:"kottayam"};enterWorld()}}
async function boot(session){user=session.user;await supabase.realtime.setAuth(session.access_token);const{data,error}=await supabase.from("profiles").select("*").eq("id",user.id).maybeSingle();if(error)throw error;$("login").hidden=true;if(data){profile=data;enterWorld()}else $("profile-screen").hidden=false}
$("logout").onclick=()=>supabase?safe(async()=>{await supabase.auth.signOut();location.reload()}):location.reload();

let scene,camera,renderer,avatar,car,driving=false,vertical=0,jumpHeight=0,wallet=1250,job=false,activities=0;const keys=new Set();
const material=color=>new THREE.MeshStandardMaterial({color,roughness:.82});
function box(parent,w,h,d,color,x=0,y=0,z=0){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(color));mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);return mesh}
function tree(x,z){const g=new THREE.Group();box(g,.3,2,.3,0x724627,0,1,0);const crown=new THREE.Mesh(new THREE.ConeGeometry(1.4,2.8,7),material(0x197744));crown.position.y=3;g.add(crown);g.position.set(x,0,z);scene.add(g)}
function sign(text){const c=document.createElement("canvas");c.width=512;c.height=96;const x=c.getContext("2d");x.fillStyle="#06271f";x.fillRect(0,0,512,96);x.fillStyle="#effff8";x.font="bold 30px sans-serif";x.textAlign="center";x.fillText(text,256,60);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c)}));s.scale.set(6,1.1,1);return s}
function building(x,z,color,name){const g=new THREE.Group();box(g,5,3.6,4,color,0,1.8,0);box(g,1.1,2,.2,0x3b2418,0,1,2.1);const s=sign(name);s.position.y=4.3;g.add(s);g.position.set(x,0,z);scene.add(g)}
function person(){const g=new THREE.Group();box(g,1,1.7,.65,profile.gender==="female"?0xbd3f7c:0x35d48f,0,1.65,0);const h=new THREE.Mesh(new THREE.SphereGeometry(.43,16,12),material(0xb97954));h.position.y=2.85;g.add(h);box(g,.32,1.2,.35,0x22304c,-.28,.6,0);box(g,.32,1.2,.35,0x22304c,.28,.6,0);return g}
function setupWorld(){scene=new THREE.Scene();scene.background=new THREE.Color(0x8bd0dd);scene.fog=new THREE.Fog(0x8bd0dd,50,120);camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,220);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;$("world").append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xd8ffff,0x315226,2.4));const sun=new THREE.DirectionalLight(0xfff1c5,2.8);sun.position.set(-20,35,10);sun.castShadow=true;scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),material(0x367b48));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);box(scene,10,.12,180,0x2b3435,0,.07,0);box(scene,180,.12,10,0x2b3435,0,.08,0);for(let i=-75;i<=75;i+=12){box(scene,.3,.16,4,0xffe46b,-1,.15,i);box(scene,.3,.16,4,0xffe46b,1,.15,i)}for(let i=0;i<38;i++)tree((Math.random()-.5)*150,(Math.random()-.5)*150);building(-12,-12,0xf1a84a,"TTK STORES · KOTTAYAM");building(14,-18,0xf6e5b7,"KERALA CAFE");building(-16,18,0xe9f0e7,"COMMUNITY HALL");building(19,17,0xe07855,"MARKET");avatar=person();avatar.position.set(0,0,5);scene.add(avatar);car=new THREE.Group();box(car,2.4,.7,4,0xe3aa18,0,.75,0);box(car,2,.75,2,0x185e65,0,1.35,-.2);car.position.set(5,0,3);scene.add(car);camera.position.set(0,8,13);addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});animate()}
function animate(){requestAnimationFrame(animate);const dt=Math.min(.04,1/60),target=driving?car:avatar;let x=0,z=0;if(keys.has("ArrowLeft")||keys.has("KeyA"))x--;if(keys.has("ArrowRight")||keys.has("KeyD"))x++;if(keys.has("ArrowUp")||keys.has("KeyW"))z--;if(keys.has("ArrowDown")||keys.has("KeyS"))z++;if(x||z){const n=Math.hypot(x,z),speed=driving?12:6;target.position.x+=x/n*speed*dt;target.position.z+=z/n*speed*dt;target.rotation.y=Math.atan2(x,z)}if(!driving){vertical-=22*dt;jumpHeight+=vertical*dt;if(jumpHeight<0){jumpHeight=0;vertical=0}avatar.position.y=jumpHeight}else avatar.position.copy(car.position).add(new THREE.Vector3(0,1.4,0));camera.position.lerp(new THREE.Vector3(target.position.x,target.position.y+7,target.position.z+11),.08);camera.lookAt(target.position.x,target.position.y+1,target.position.z);renderer.render(scene,camera)}
addEventListener("keydown",e=>{keys.add(e.code);if(e.code==="Space"&&!jumpHeight)vertical=8});addEventListener("keyup",e=>keys.delete(e.code));document.querySelectorAll("[data-move]").forEach(b=>{const c=b.dataset.move;b.onpointerdown=()=>keys.add(c);b.onpointerup=b.onpointerleave=()=>keys.delete(c)});$("jump").onclick=()=>{if(!jumpHeight)vertical=8};$("drive").onclick=()=>{if(!driving&&avatar.position.distanceTo(car.position)>7)return notify("Walk closer to the auto-rickshaw.");driving=!driving;$("drive").textContent=driving?"Exit":"Drive"};$("job").onclick=()=>{if(job){job=false;wallet+=250;activities=Math.min(3,activities+1);notify("Delivery completed. ₹250 earned!")}else{job=true;notify("Delivery started. Explore town, then press Job again.")}updateHud()};
function updateHud(){$("player-info").textContent=`${profile.name} · Lv. 1`;$("wallet").textContent=`₹${wallet.toLocaleString("en-IN")}`;$("mission-info").textContent=`Complete 3 activities (${activities}/3)`;$("job-info").textContent=job?"Delivery active — explore and press Job to finish.":"Walk around Kottayam. Start a delivery job."}

async function refreshPeople(){if(!user)return;const[p,r]=await Promise.all([supabase.from("profiles").select("id,name,home_district,gender").limit(100),supabase.from("follow_requests").select("*")]);if(p.error)throw p.error;if(r.error)throw r.error;profiles=new Map(p.data.map(v=>[v.id,v]));requests=r.data;renderPeople()}
function button(parent,label,fn,secondary=false){const b=document.createElement("button");b.textContent=label;if(secondary)b.className="secondary";b.onclick=()=>safe(fn);parent.append(b)}
function renderPeople(){const root=$("people");root.replaceChildren();const list=[...profiles.values()].filter(p=>p.id!==user.id);if(!list.length){root.textContent="No other profiles yet.";return}for(const p of list){const card=document.createElement("div");card.className="person";const title=document.createElement("strong");title.textContent=p.name;const district=document.createElement("small");district.textContent=districts.find(d=>d.id===p.home_district)?.name||p.home_district;const actions=document.createElement("div");actions.className="row";const req=requests.find(r=>(r.requester_id===user.id&&r.target_id===p.id)||(r.target_id===user.id&&r.requester_id===p.id));if(!req)button(actions,"Follow",async()=>{const{error}=await supabase.from("follow_requests").insert({requester_id:user.id,target_id:p.id});if(error)throw error;refreshPeople()});else if(req.status==="accepted"){button(actions,"Message",async()=>{activeDM=p.id;$("chat-title").textContent=p.name;loadMessages()});button(actions,"Disconnect",async()=>{await supabase.from("follow_requests").delete().eq("id",req.id);activeDM=null;refreshPeople()},true)}else if(req.target_id===user.id&&req.status==="pending"){button(actions,"Accept",async()=>{await supabase.from("follow_requests").update({status:"accepted"}).eq("id",req.id);refreshPeople()});button(actions,"Reject",async()=>{await supabase.from("follow_requests").update({status:"rejected"}).eq("id",req.id);refreshPeople()},true)}else{const s=document.createElement("small");s.textContent=req.status;actions.append(s)}card.append(title,district,actions);root.append(card)}}
async function loadMessages(){if(!user)return;const q=activeDM?supabase.from("dm_messages").select("*").or(`and(sender_id.eq.${user.id},receiver_id.eq.${activeDM}),and(sender_id.eq.${activeDM},receiver_id.eq.${user.id})`).order("created_at",{ascending:false}).limit(50):supabase.from("district_messages").select("*").eq("room","kottayam").order("created_at",{ascending:false}).limit(50);const{data,error}=await q;if(error)throw error;const root=$("messages");root.replaceChildren();for(const m of [...data].reverse()){const row=document.createElement("div");row.className="message";const head=document.createElement("strong");head.textContent=`${profiles.get(m.sender_id)?.name||"Player"} · ${new Date(m.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}`;const body=document.createElement("span");body.textContent=m.body;row.append(head,body);root.append(row)}root.scrollTop=root.scrollHeight}
$("chat-form").onsubmit=e=>safe(async()=>{e.preventDefault();if(!user)return notify("Configure Supabase to use chat.");const body=$("chat-input").value.trim();const result=activeDM?await supabase.from("dm_messages").insert({sender_id:user.id,receiver_id:activeDM,body}):await supabase.from("district_messages").insert({room:"kottayam",sender_id:user.id,body});if(result.error)throw result.error;$("chat-input").value="";loadMessages()});$("group").onclick=()=>{activeDM=null;$("chat-title").textContent="Kottayam community";safe(loadMessages)};$("refresh").onclick=()=>safe(refreshPeople);
function drawMap(){const c=$("map"),x=c.getContext("2d");x.fillStyle="#143d48";x.fillRect(0,0,c.width,c.height);x.strokeStyle="#69d9a7";x.lineWidth=5;x.beginPath();districts.forEach((d,i)=>{const px=42+(d.lon-74.8)*92,py=18+(12.7-d.lat)*70;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();for(const d of districts){const px=42+(d.lon-74.8)*92,py=18+(12.7-d.lat)*70;x.fillStyle=d.id==="kottayam"?"#ffe46b":"#fff";x.beginPath();x.arc(px,py,d.id==="kottayam"?6:3,0,7);x.fill()}x.fillText("Kottayam",140,225)}
$("travel").onclick=()=>{const d=districts.find(v=>v.id===$("travel-district").value);$("location").textContent=d.name;notify(`Fast travelled to ${d.name}.`)};$("menu").onclick=()=>$("sidebar").classList.add("open");$("close").onclick=()=>$("sidebar").classList.remove("open");
async function enterWorld(){if(worldStarted)return;worldStarted=true;$("login").hidden=$("profile-screen").hidden=true;$("game").hidden=false;setupWorld();drawMap();updateHud();if(user){await refreshPeople();await loadMessages();supabase.channel(`world-${user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"district_messages"},()=>!activeDM&&safe(loadMessages)).on("postgres_changes",{event:"*",schema:"public",table:"dm_messages"},()=>activeDM&&safe(loadMessages)).on("postgres_changes",{event:"*",schema:"public",table:"follow_requests"},()=>safe(refreshPeople)).subscribe()}}
